--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pedhot-Dev/HubSpawn
build-by-default: true
branches:
- master
projects:
  HubSpawn:
    path: ""
    libs:
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
...
